sonar.projectKey=cm-acr-authservice
sonar.projectName=cm-acr-authservice
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.language=java
sonar.java.binaries=.
sonar.qualitygate.ignoreSmallChanges=false
